import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/comingSoon/Footer";
import LenisWrapper from "./ui/LenisWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Code Hype",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased animate-gradient-x contrast-[1.1] brightness-110`}
      >
        <LenisWrapper>
          {children}
         <Footer />
        </LenisWrapper>
      </body>
    </html>
  );
}
